# ------ Samples ------
samples: '*' # specify a list samples to use or '*' to use all samples

# ------ Resources ------
threads : 8 # single task nb threads

# ------ Assembly parameters ------ 
data: /mnt/mydatalocal/Projects/STRONG_AD/data  # path to data folder

# ----- Annotation database -----
cog_database: /home/ubuntu/data/public/teachdata/ebame/Quince-data-2021/COG/Cog # COG database


gtdb_path: "/home/ubuntu/data/public/teachdata/ebame/Quince-data-2021/release202"

# ----- Binning parameters ------
concoct:
    contig_size: 1000

read_length: 150
assembly: 
    assembler: spades
    k: [77]
    mem: 2000
    threads: 48

# ----- BayesPaths parameters ------
bayespaths:
    nb_strains: 16
    min_orf_number_to_merge_bins: 10
    min_orf_number_to_run_a_bin: 10
    percent_unitigs_shared: 0.1
    nb_strains: 8
    nmf_runs: 1
    max_giter: 1 

#----- DESMAN parameters ------
desman:
    execution: 1
    nb_haplotypes: 10
    nb_repeat: 5
    min_cov: 1


# -----  Evaluation ------
evaluation:
    execution: 0
    genomes: "/mnt/gpfs/chris/Projects/STRONG_Runs/Test/Eval" # path to refferences genomes 
